[general]
default_module = "app" # The module to run when no prefix is matched
empty_module = "app" # run with an empty prompt
exec_cmd = "sh -c" # The exec command of your shell, default to sh
# for example: "bach -c" for bash; "zsh -c" for zsh. This can also runs wm exec commands, like hyprctl dispatch exec
vi_mode = true # set true to use vi keybinds, false to use emacs keybinds; default to emacs
esc_to_abort = true # allow to quit with esc keypress; a useful option for vi users
cheatsheet_entry = "?" # when entered, otter-launcher will show a list of configured modules
cheatsheet_viewer = "less -R; clear" # the program that otter-launcher will pipe cheatsheet into
clear_screen_after_execution = false # useful when chafa image flash back after module execution
loop_mode = false # in loop mode, otter-launcher won't quit after running a module, useful when using scratchpad
external_editor = "" # if set, pressing ctrl+e (or pressing v in vi normal mode) will edit the input field in the specified program; default to no external editor
#callback = "" # if set, otter-launcher will run the command after a module is executed; for example, it can call swaymsg to adjust window size


# ASCII color codes are allowed with these options. However, \x1b should be replaced with \u001B (unicode escape) because the rust toml crate cannot read \x as an escaped character...
[interface]
# use three quotes to write longer commands
header = """
 \u001B[34;1m  >\u001B[0m $USER@$(echo $HOSTNAME)                \u001B[31m\u001B[0m $(cat /proc/loadavg | cut -d ' ' -f 1)  \u001B[33m󰍛\u001B[0m $(free -h | awk 'FNR == 2 {print $3}' | sed 's/i//')
    \u001B[34;1m>\u001B[0;1m """
# Run a shell command and make the stdout printed above the header
header_cmd = ""
header_cmd_trimmed_lines = 0 # Remove a number of lines from header_cmd output, in case of some programs printing excessive empty lines at the end of its output
header_concatenate = false # print header and header_cmd output at the same line, default to false
list_prefix = "      "
selection_prefix = "    \u001B[31;1m> "
place_holder = "type and search"
default_module_message = "      \u001B[33msearch\u001B[0m the internet" # if set, the text will be shown when the default module is in use
empty_module_message = "" # the text to show when empty module is in use
suggestion_mode = "list" # available options: list, hint
suggestion_lines = 4 # length of the suggestion list, set to 0 to disable suggestions and tab completion
indicator_with_arg_module = "\u001B[31m^\u001B[0m " # a sign showing whether the module should run with an argument
indicator_no_arg_module = "\u001B[31m$\u001B[0m "
prefix_padding = 3 # format prefixes to have a uniformed width; prefixes will be padded with spaces to have a least specified number of chars
# below color options affect all modules; per-module coloring is allowed by using ascii color codes at each module's configurations
prefix_color = "\u001B[33m"
description_color = "\u001B[38m"
place_holder_color = "\u001B[30m"
hint_color = "\u001B[30m" # the color of hint mode suggestions
# move the whole interface rightward or upward, easier for styling with chafa image
move_right = 0
move_up = 0


# Modules are defined as followed
[[modules]]
description = "search with google"
prefix = "gg"
# try wm's exec command if 'setsid -f' does not work, eg. 'hyprctl dispatch exec'
cmd = "setsid -f xdg-open 'https://www.google.com/search?q={}'"
with_argument = true # If "with_argument" is true, the {} in the cmd value will be replaced with user input. If the field is not explicitly set, will be taken as false.
url_encode = true # "url_encode" should be true if the module is set to call webpages, as this ensures special characters in url being readable to browsers. It'd better be false with shell scripts. If the field is not explicitly set, will be taken as false.

[[modules]]
description = "launch desktop programs"
prefix = "app"
cmd = """
swaymsg [app_id="otter-launcher"] resize set width 600px height 600px
sway-launcher-desktop
"""

[[modules]]
description = "power menu with fzf"
prefix = "po"
cmd = """
function power {
if [[ -n $1 ]]; then
case $1 in
"logout") session=`loginctl session-status | head -n 1 | awk '{print $1}'`; loginctl terminate-session $session ;;
"suspend") systemctl suspend ;;
"hibernate") systemctl hibernate ;;
"reboot") systemctl reboot ;;
"shutdown") systemctl poweroff ;;
esac fi }
power $(echo -e 'reboot\nshutdown\nlogout\nsuspend\nhibernate' | fzf --reverse --no-scrollbar --padding 1,3 --prompt 'Power Menu: ' | tail -1)
"""

[[modules]]
description = "launch program in a new terminal"
prefix = "sh"
cmd = "setsid -f $TERM -e {}"
with_argument = true

[[modules]]
description = "search nix wiki"
prefix = "nixw"
cmd = "setsid -f xdg-open https://wiki.nixos.org/w/index.php?search={} && swaymsg '[app_id=firefox] focus'"
with_argument = true
url_encode = true

[[modules]]
description = "search for nix packages"
prefix = "nix"
cmd = "setsid -f xdg-open https://search.nixos.org/packages?query={} && swaymsg '[app_id=firefox] focus'"
with_argument = true
url_encode = true

[[modules]]
description = "kill a program"
prefix = "kill"
cmd = "pkill -f {}"
with_argument = true
url_encode = true

[[modules]]
description = "search for nix packages"
prefix = "apk"
cmd = """
xdg-open 'https://apkpure.com/search?q={}'
xdg-open 'https://www.apkmirror.com/?post_type=app_release&searchtype=apk&bundles%5B%5D=apkm_bundles&bundles%5B%5D=apk_files&s={}'
xdg-open 'https://apkcombo.com/search/{}'
swaymsg '[app_id=firefox] focus'
"""
with_argument = true
url_encode = true

[[modules]]
description = "connect to a vpn"
prefix = "vpn"
cmd = """
selected=$(echo -e "$(nmcli connection show | rg ' vpn | wireguard ' | cut -d ' ' -f 1)" | fzf --reverse --padding 1,3 --prompt 'VPNs: ')
 
if [ "$(nmcli connection show --active | rg "$selected")" ]
  then
    nmcli connection down "$selected"
  else
    nmcli connection up "$selected" --ask
fi
"""
